from django.conf.urls import url, include
from xpgg_oms.views import views_test, v_login, v_index, v_cmdb,v_network_tool, v_saltstack, v_nginx, v_release_sys, v_cdn

# drf的router
from rest_framework.routers import DefaultRouter

# 实例化router对象
router = DefaultRouter()
# 通过router注册方式配置路由，快准狠
router.register(r'appreleaselist', views_test.AppReleaseListViewSet, base_name='appreleaselist')

urlpatterns = [
    # url(r'^$',views.index,name='index'),
    url(r'^$', v_index.index, name='index'),
    url(r'^index$', v_index.index, name='index'),
    url(r'^index_ajax$', v_index.index_ajax, name='index_ajax'),
    url(r'^login/$', v_login.do_login, name='login'),
    url(r'^logout/$', v_login.do_logout, name='logout'),
    url(r'^module_deploy/$', v_saltstack.module_deploy, name='module_deploy'),
    url(r'^net_tool/$', v_network_tool.net_tool, name='net_tool'),
    url(r'^minion_client_install/$', v_saltstack.minion_client_install, name='minion_client_install'),
    url(r'^minion_manage/$', v_saltstack.minion_manage, name='minion_manage'),
    url(r'^minion_manage_ajax/$', v_saltstack.minion_manage_ajax, name='minion_manage_ajax'),
    url(r'^saltkey_manage/$', v_saltstack.saltkey_manage, name='saltkey_manage'),
    url(r'^salt_key_global/$', v_saltstack.salt_key_global, name='salt_key_global'),
    url(r'^salt_test_ping/$', v_saltstack.salt_test_ping, name='salt_test_ping'),
    url(r'^salt_key_delete/$', v_saltstack.salt_key_delete, name='salt_key_delete'),
    url(r'^salt_key_denied_delete/$', v_saltstack.salt_key_denied_delete, name='salt_key_denied_delete'),
    url(r'^salt_key_accept/$', v_saltstack.salt_key_accept, name='salt_key_accept'),
    url(r'^salt_key_reject/$', v_saltstack.salt_key_reject, name='salt_key_reject'),
    url(r'^salt_cmd_manage/$', v_saltstack.salt_cmd_manage, name='salt_cmd_manage'),
    url(r'^salt_cmd_manage_ajax/$', v_saltstack.salt_cmd_manage_ajax, name='salt_cmd_manage_ajax'),
    url(r'^salt_exe/$', v_saltstack.salt_exe, name='salt_exe'),
    url(r'^salt_exe_ajax/$', v_saltstack.salt_exe_ajax, name='salt_exe_ajax'),
    url(r'^salt_tool/$', v_saltstack.salt_tool, name='salt_tool'),
    url(r'^salt_tool_ajax/$', v_saltstack.salt_tool_ajax, name='salt_tool_ajax'),
    url(r'^salt_file_manage/$', v_saltstack.salt_file_manage, name='salt_file_manage'),
    url(r'^salt_file_manage_ajax/$', v_saltstack.salt_file_manage_ajax, name='salt_file_manage_ajax'),
    url(r'^server_list/$', v_cmdb.server_list, name='server_list'),
    url(r'^server_list_ajax/$', v_cmdb.server_list_ajax, name='server_list_ajax'),
    url(r'^server_list_template_down/$', v_cmdb.server_list_template_down, name='server_list_template_down'),
    url(r'^server_list_down/$', v_cmdb.server_list_down, name='server_list_down'),
    url(r'^network_list/$', v_cmdb.network_list, name='network_list'),
    url(r'^network_list_ajax/$', v_cmdb.network_list_ajax, name='network_list_ajax'),
    url(r'^network_list_template_down/$', v_cmdb.network_list_template_down, name='network_list_template_down'),
    url(r'^network_list_down/$', v_cmdb.network_list_down, name='network_list_down'),
    url(r'^nginx_upstream/$', v_nginx.nginx_upstream, name='nginx_upstream'),
    url(r'^nginx_manage/$', v_nginx.nginx_manage, name='nginx_manage'),
    url(r'^nginx_conflist/$', v_nginx.nginx_conflist, name='nginx_conflist'),
    url(r'^nginx_reload/$', v_nginx.nginx_reload, name='nginx_reload'),
    url(r'^nginx_upstreamserver_add/$', v_nginx.nginx_upstreamserver_add, name='nginx_upstreamserver_add'),
    url(r'^app_release/$', v_release_sys.app_release, name='app_release'),
    url(r'^app_release_test/$', v_release_sys.app_release_test, name='app_release_test'),
    url(r'^app_release_ajax/$', v_release_sys.app_release_ajax, name='app_release_ajax'),
    url(r'^app_group/$', v_release_sys.app_group, name='app_group'),
    url(r'^app_group/app_group_members_manage/$', v_release_sys.app_group_members_manage, name='app_group_members_manage'),
    url(r'^app_group_ajax/$', v_release_sys.app_group_ajax, name='app_group_ajax'),
    url(r'^app_auth/$', v_release_sys.app_auth, name='app_auth'),
    url(r'^app_auth/app_auth_app_manage/$', v_release_sys.app_auth_app_manage, name='app_auth_app_manage'),
    url(r'^app_auth/app_auth_app_group_manage/$', v_release_sys.app_auth_app_group_manage, name='app_auth_app_group_manage'),
    url(r'^app_auth_ajax/$', v_release_sys.app_auth_ajax, name='app_auth_ajax'),
    url(r'^huawei_cdn/$', v_cdn.huawei_cdn, name='huawei_cdn'),
    url(r'^h5_issue/$', v_release_sys.h5_issue, name='h5_issue'),
    url(r'^h5_svn_co/$', v_release_sys.h5_svn_co, name='h5_svn_co'),
    url(r'^h5_svn_zip/$', v_release_sys.h5_svn_zip, name='h5_svn_zip'),
    url(r'^h5_svn_push/$', v_release_sys.h5_svn_push, name='h5_svn_push'),
    url(r'^h5_svn_unzip/$', v_release_sys.h5_svn_unzip, name='h5_svn_unzip'),
    url(r'^h5_file/$', v_release_sys.h5_file, name='h5_file'),
    # url(r'^nginx_add/$',views.nginx_add,name='nginx_add'),
    # url(r'^archive/$',views.archive,name='archive'),
    url(r'^test/$', v_cmdb.server_list, name='test'),
    url(r'^api/', include(router.urls)),
]